### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by dirdi** [benknoble/vim-hex#2]
If one loads a big file into the buffer (like 100 MiB), conversion takes some time. This is of course inevitable when the file is transformed for the first time to hex view. But every time one leaves insert mode, the conversion is done two times, to update the ASCII column. If no additional bytes were added or existing bytes were removed, it would be sufficient and probably much faster to only update the ASCII column of lines with changed bytes.

At least an option should be implemented to disable the automatic updates of the ASCII column.

**Comment by benknoble** [comment]
Thanks for filing this @dirdi; I hadn't considered large files...

Can you try the following and let me know if it solves your first problem? I can easily add the option to disable automatic updates (which you can then trigger manually with `:call hex#update()`) too.

In `autoload/hex.vim`, [line 60](https://github.com/benknoble/vim-hex/blob/e0f0958ca119f305361a5a1dc1e2f59ca1efa0ca/autoload/hex.vim#L60) defines `hex#update`. Try moving the `if !l:modified` line further up, so that the function says

```vim
function hex#update() abort
  let l:changed = s:hex_changed()
  if !l:changed
    call s:hex_save_cursor()
    call hex#rev()
    call hex#dump()
    call s:hex_restore_cursor()
    setlocal nomodified
  endif
endfunction
```

Other things I can think of to try are

- testing `&modified` directly

**Comment by benknoble** [comment]
Ah, seems I jumped the gun. Can you try the modifications in the latest commit (d50b6776ff74f5bca741b58af0da4673473bf057)?

**Comment by dirdi** [comment]
Sorry for the long delay. Yes, d50b677 speed things up if one leaves input mode without modifications and the `g:hex_no_update` option works as expected. Thank you!

**Comment by benknoble** [comment]
@dirdi glad it works for you. I'll merge the PR to fix this.
